### ISSUE TITLE
codeinjection_head missing on getposts

### ISSUE THREAD

**Issue by KasperVesth** [grantwinney/GhostSharp#28]
Hi, I don't know if you still maintain this, but I figured it was worth a shot. I am using it and loving it, but I no matter what I do, I never get codeinjection_head back from the getposts or getpostbyid methods. I am getting this by making my own call, but I have made something that means that all my posts has it, so I need it for all of my update calls to not overwrite the values :D 

Is there any chance you could get that working? :)

**Comment by grantwinney** [comment]
It's been quite awhile since I touched this. Looks like the API changed again, so I'd have some things to figure out there. I depend heavily on RestSharp, and they decided to [break some things](https://restsharp.dev/v107/) with a recent update. I'd like to get this updated, but can't say when I'll have the time to do it for sure.

**Comment by KasperVesth** [comment]
Sounds great :) Everything else seems to work great as well, so hopefully it's not a large change.

**Comment by grantwinney** [comment]
Took forever for me to get around to updating this, but I just uploaded a big update to nuget.org. I have a few tests where I test whether that value is coming back, and it is now. I don't _think_ I updated anything around that piece.. maybe I did, or maybe some past version of their API wasn't returning all the values like it should.
