### ISSUE TITLE
Publish GhostSharp as Nuget Package

### ISSUE THREAD

**Issue by renehernandez** [grantwinney/GhostSharp#8]
I am planning to use GhostSharp as a dependency for a statistic site I am building using dotnetcore.

Unfortunately, GhostSharp is not yet available in NuGet.

I have already forked the repo and I am planning to put automatic versioning release to Nuget.

Will keep you posted.

Regards,
Rene

By the way, @grantwinney  nice work

**Comment by grantwinney** [comment]
Thanks Rene. I hadn't thought of putting it out on NuGet but if you get it to work that'd be cool.

Just FYI, check out the other "issues" I created too... it's been awhile since I touched this repo but I know there were some things I wanted this project to support that it currently doesn't. At some point, I'd like to go back and finish those up.

**Comment by grantwinney** [comment]
I rewrote it for the new Content API (v2) using .NET Standard, and published it to NuGet.
